### ISSUE TITLE
FEATURE: API Permissions

### ISSUE THREAD

**Issue by DynamoRed** [RMR-Inc/loyaltycard_web#11]
### Feature Description

- [x] Définir qui peut faire quelle requête sur notre api
- [x] Définir les résultats affichés selon la personne qui les demandes

*Une fois fait, mise en place de ces mesures sur l'API par @DynamoRed*

**Comment by Dropaa** [comment]
Création des permissions de l'API à l'aide du modèle REST CRUD ( create, read, update, delete).
3 participants : Système, Employé LoyaltyCard, Utilisateur (ou User).
[Permissions.zip](https://github.com/RMR-Inc/loyaltycard_web/files/8193115/Permissions.zip)
